[package]
name = "chatbox"
version = "0.1.0"
authors = ["bruno <bruno.pereira@4effect.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = "1.4.0"