[package]
name = "paho-mqtt-poc"
version = "0.1.0"
authors = ["bruno <bruno.pereira@4effect.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paho-mqtt = "0.7.1"